Lesson03/ServerlessClient/Models/Transaction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ServerlessClient.Models
{
    public class Transaction
    {
        public DateTime ExecutionTime { get; set; }
        public Decimal Amount { get; set; }
    }
}

Lesson03/ServerlessClient/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;

namespace ServerlessClient.Models
{
    public class User
    {
        public string EmailAddress { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Password { get; set; }
    }
}

Lesson03/ServerlessClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServerlessClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lesson03/ServerlessClient/Controllers/TransactionController.cs
using Newtonsoft.Json;
using ServerlessClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ServerlessClient.Controllers
{
    public class TransactionController : Controller
    {
        private HttpClient http = new HttpClient();
        private string key = "Your Function Key";
        // GET: Transaction
        public ActionResult Index()
        {
            // Add your key as a query parameter.
            var builder = new UriBuilder("Your Function Address here");
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["code"] = key;
            builder.Query = query.ToString();

            var url = builder.ToString();
            var response = http.GetAsync(url);
            var result = response.Result.Content.ReadAsStringAsync().Result;
            var transactions = JsonConvert.DeserializeObject<List<Transaction>>(result);

            // Useful code for debugging front end
            /*
                var transactions = new List<Transaction>
                {
                    new Transaction
                    {
                        Amount = 22.3m,
                        ExecutionTime = new DateTime()
                    }
                };
            */
            return View(transactions);
        }

        
        // GET: Transaction/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Transaction/Create
        [HttpPost]
        public ActionResult Create(Transaction transaction)
        {
            // Add your key as a query parameter.
            var builder = new UriBuilder("Your Function Address here");
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["code"] = key;
            builder.Query = query.ToString();

            var url = builder.ToString();
            var stringifiedTransaction = JsonConvert.SerializeObject(transaction);
            var content = new StringContent(stringifiedTransaction, Encoding.UTF8, "application/json");
            var result = http.PostAsync(url, content).Result;
            // Usually do some error handling here. 

            return View();
        }

        // GET: Transaction/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Transaction/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Transaction/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Transaction/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Lesson03/ServerlessClient/Controllers/UserController.cs
using Newtonsoft.Json;
using ServerlessClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ServerlessClient.Controllers
{
    public class UserController : Controller
    {
        private HttpClient http = new HttpClient();
        private string key = "Your Function Key";
        // GET: Transaction
        public ActionResult Index()
        {
            // Add your key as a query parameter.
            var builder = new UriBuilder("Your Function Address here");
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["code"] = key;
            builder.Query = query.ToString();

            var url = builder.ToString();
            var response = http.GetAsync(url);
            var result = response.Result.Content.ReadAsStringAsync().Result;
            var users = JsonConvert.DeserializeObject<List<User>>(result);

            // Useful code for debugging front end
            /*
                var transactions = new List<Transaction>
                {
                    new Transaction
                    {
                        Amount = 22.3m,
                        ExecutionTime = new DateTime()
                    }
                };
            */
            return View(users);
        }


        // GET: Transaction/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(User user)
        {
            // Add your key as a query parameter.
            var builder = new UriBuilder("Your Function Address here");
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["code"] = key;
            builder.Query = query.ToString();

            var url = builder.ToString();
            var stringifiedUser = JsonConvert.SerializeObject(user);
            var content = new StringContent(stringifiedUser, Encoding.UTF8, "application/json");
            var result = http.PostAsync(url, content).Result;
            // Usually do some error handling here. 

            return View();
        }

        // GET: Transaction/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Transaction/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Transaction/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Transaction/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Lesson03/ServerlessClient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lesson03/ServerlessClient/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lesson03/ServerlessClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@{
    Html.RenderAction("Index", "Transaction");
}

Lesson03/ServerlessClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lesson03/ServerlessClient/Views/Transaction/Create.cshtml
@model ServerlessClient.Models.Transaction


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ExecutionTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExecutionTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExecutionTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lesson03/ServerlessClient/Views/Transaction/Index.cshtml
@model IEnumerable<ServerlessClient.Models.Transaction>

<h2>Transactions</h2>
<table class="table">
    <tr>
        <th>Amount</th>
        <th>Time of Transaction</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Amount
            </td>
            <td>
                @item.ExecutionTime
            </td>
        </tr>
    }

</table>
@{
    Html.RenderAction("Create", "Transaction");
}

Lesson03/ServerlessClient/Views/User/Create.cshtml
@model ServerlessClient.Models.User

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lesson03/ServerlessClient/Views/User/Index.cshtml
@model IEnumerable<ServerlessClient.Models.Transaction>

<h2>Transactions</h2>
<table class="table">
    <tr>
        <th>Amount</th>
        <th>Time of Transaction</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Amount
            </td>
            <td>
                @item.ExecutionTime
            </td>
        </tr>
    }

</table>
@{
    Html.RenderAction("Create", "Transaction");
}